### ISSUE TITLE
Move Firehose/Substreams supported endpoints to another repo

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/pyfirehose#6]
- [ ] Perhaps create a "Awesome Substreams" repo under Pinax with all this relevant information

For using [Pinax](https://pinax.network) based endpoints, go to https://pinax.network/ and create a free account for registering an API key.

For using [StreamingFast](https://streamingfast.io) based endpoints, go to https://app.streamingfast.io/ and create a free account for registering an API key.

| Auth provider | Blockchain          | Block protobuf       | gRPC endpoint                             |
|---------------|---------------------|----------------------|-------------------------------------------|
| eosnation     | EOS                 | sf.antelope.type.v1  | [eos.firehose.eosnation.io:9001](http://eos.firehose.eosnation.io:9001)      |
| eosnation     | EOS                 | dfuse.eosio.codec.v1 | [eos.firehose.eosnation.io:9000](http://eos.firehose.eosnation.io:9000)      |
| eosnation     | WAX                 | dfuse.eosio.codec.v1 | [wax.firehose.eosnation.io:9000](http://wax.firehose.eosnation.io:9000)      |
| eosnation     | Kylin               | dfuse.eosio.codec.v1 | [kylin.firehose.eosnation.io:9000](http://kylin.firehose.eosnation.io:9000)    |
| eosnation     | Jungle4             | dfuse.eosio.codec.v1 | [jungle4.firehose.eosnation.io:9000](http://jungle4.firehose.eosnation.io:9000)  |

#### Pending implementation

| Auth provider | Blockchain          | Block protobuf      | gRPC endpoint                              |
|---------------|---------------------|---------------------|--------------------------------------------|
| streamingfast | Ethereum Mainnet    | sf.ethereum.type.v2 | [mainnet.eth.streamingfast.io:443](http://mainnet.eth.streamingfast.io:443)     |
| streamingfast | Görli               | sf.ethereum.type.v2 | [goerli.eth.streamingfast.io:443](http://goerli.eth.streamingfast.io:443)      |
| streamingfast | Polygon Mainnet     | sf.ethereum.type.v2 | [polygon.streamingfast.io:443](http://polygon.streamingfast.io:443)         |
| streamingfast | BNB                 | sf.ethereum.type.v2 | [bnb.streamingfast.io:443](http://bnb.streamingfast.io:443)             |
| streamingfast | Near Mainnet        | sf.near.type.v1     | [mainnet.near.streamingfast.io:443](http://mainnet.near.streamingfast.io:443)    |
| streamingfast | Near Testnet        | sf.near.type.v1     | [testnet.near.streamingfast.io:443](http://testnet.near.streamingfast.io:443)    |
| streamingfast | Solana Mainnet-beta | sf.solana.type.v1   | [mainnet.sol.streamingfast.io:443](http://mainnet.sol.streamingfast.io:443)     |
| streamingfast | Arweave Mainnet     | sf.arweave.type.v1  | [mainnet.arweave.streamingfast.io:443](http://mainnet.arweave.streamingfast.io:443) |
| streamingfast | Aptos Testnet       | aptos.extractor.v1  | [testnet.aptos.streamingfast.io:443](http://testnet.aptos.streamingfast.io:443)   |

**Comment by DenisCarriere** [comment]
Started with `pinax-network/endpoint` repo and we can eventually evolve it to an "Awesome" repo

https://github.com/pinax-network/endpoints

**Comment by Krow10** [comment]
Awesome Substreams repo is live here ! Don't forget to start it ⭐ 
https://github.com/pinax-network/awesome-substreams
